#!/bin/sh
exec /opt/homebrew/bin/ccls --init='{"clang++":{"extraArgs":[
    "-std=c++17",
    "-isystem/usr/local/include",
    "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1",
    "-isystem/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include",
    "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-isystem/Library/Developer/CommandLineTools/usr/include",
    "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks",
    "-isystem/opt/homebrew/bin/",
    "-isystem/opt/homebrew/Cellar/open-mpi/5.0.0/include"
]}}' "$@"

# "${CONDA_PREFIX}/include/python3.9",
# "${folder}/inc",

