require("mc.plugins-setup")
require("mc.core.options")
require("mc.core.keymaps")
require("mc.plugins.tokyonight")
require("mc.core.colorscheme")
require("mc.plugins.comment")
require("mc.plugins.nvim-tree")
require("mc.plugins.lualine")
require("mc.plugins.telescope")
require("mc.plugins.nvim-cmp")
require("mc.plugins.lsp.mason")
require("mc.plugins.lsp.lspconfig")
-- require("mc.plugins.lsp.null-ls")
require("mc.plugins.autopairs")
require("mc.plugins.treesitter")
